# ---------------------------------------------------------------------------
# spatial join predicts sites to WDPA layer.py
# Created on: 2014-06-12 17:51:45.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
WDPA_layer = "C:/GIS/Data/WDPA/WDPAmollmergeJULY/WDPAmollmergeJULY_no_biosphere_inscribed_adopted.shp"
shapefile_from_R = "C:/GIS/PA_predicts_mapping/all_sites_taxa_split_coarse_11_2014.shp"
projected_points = "C:\\GIS\\PA_predicts_mapping\\all_sites_taxa_split_coarse_11_2014_moll.shp"
output = "C:\\GIS\\PA_predicts_mapping\\predicts_wdpa_join_taxa_split_coarse_WDPA_nobiosphere_inscribed_adopted_11_2014.shp"

# Process: Define Projection
arcpy.DefineProjection_management(shapefile_from_R, "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Project to mollweide
arcpy.Project_management(shapefile_from_R,projected_points,"PROJCS['World_Mollweide',GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],PROJECTION['Mollweide'],PARAMETER['False_Easting',0.0],PARAMETER['False_Northing',0.0],PARAMETER['Central_Meridian',0.0],UNIT['Meter',1.0]]","#","GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]]")

# Process: Spatial Join
arcpy.SpatialJoin_analysis(shapefile_from_R, WDPA_layer, output, "JOIN_ONE_TO_MANY", "KEEP_ALL")
